# Each new term in the Fibonacci sequence is generated by adding the previous 
# two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.


seq=Hash[0 => 1, 1 => 2]

n = seq[seq.count - 2] + seq[seq.count - 1]

sum = []


while n < 4000000

  seq[seq.count] = seq[seq.count - 2] + seq[seq.count - 1]

  n = seq[seq.count - 2] + seq[seq.count - 1]

end

seq.each do |n|
  if n.last.even?
    sum.push n.last
  end
end

#puts sum
puts sum.inject(:+)
#puts seq



